[variables]
NIXPACKS_SPA_OUTPUT_DIR = "client/dist"

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[staticAssets]
Caddyfile = '''
# global options
{
 admin off
 persist_config off
 auto_https off
 log {
  format json
 }
 servers {
  trusted_proxies static private_ranges 100.0.0.0/8
 }
}

:{$PORT:3000} {
 log {
  format json
 }

 rewrite /health /*

 root * ../app/client/dist

 encode gzip

 file_server

 try_files {path} /index.html
}'''
